### ISSUE TITLE
There is No Back Button.

### ISSUE THREAD

**Issue by Wameedh** [imougy/Planet-Earth-Bugs#21] opened 2016-01-21 22:55 UTC
<h2>Steps:</h2>
1. Open the app.
2. Go to Activities.
3. Tap on Currencies.

![evernote camera roll 20160121 144150](https://cloud.githubusercontent.com/assets/13262511/12497040/40211a16-c04e-11e5-85b9-189d437d0e6a.png)

<h2>Results:</h2>

When you tap on Currencies you will navigate to a new view (Plant Earth). In the new view there is no back button on the top-left corner if you want to go back you need to tap on activities button on the bottom-left. :confused: 

![evernote camera roll 20160121 144259](https://cloud.githubusercontent.com/assets/13262511/12497076/6995a3bc-c04e-11e5-88fe-4eba17fde3d1.png)

<h2>Expectation: </h2>

When the user tap on any cell in a table view in an app, and navigate to a new view, he/she will expect to have Back button on the top-left corner to use it to get back to the previous view. :+1: 

Thank you
Wameedh :smiley:

**Comment by imougy** [comment] 2016-01-22 04:26
I needed to have Inverse button because we needed a quick way to switch currencies (USDEUR <-> EURUSD). I know it is confusing because the Back button is gone, but users will eventually get to know this is a special view that needs this button.
I will close the issue because it is by design.

**Closed as completed by imougy** 2016-01-22 04:26 UTC
Labels: enhancement
